### ISSUE TITLE
Bushes gotten by /give not growing

### ISSUE THREAD

**Issue by TimVerhaegen** [Terasology/SimpleFarming#44]
The bushes I get through /give aren't growing. If you plan a seed into the ground it does grow.

To reproduce, simply open a world (existing or new, shouldn't matter) and /give some bushes. This can be a cookiebush, but also a Cranberry or whatever berrybush. Place the BLOCK down and use the /give growthcan on it. You'll notice it's not growing/updating the fruit?

Example of what I did:
I ran the give command with as parameter these blocks: MatureCookieBerryBush, CookieBerryBush and CookieBerryBushFull - and also /give MatureBlackBerryBush, BlackBerryBush and BlackBerryBushFull. 
I placed them down like on the screenshot (check attachments) and used the can on them. Waiting for them to grow won't work either.
![bush](https://cloud.githubusercontent.com/assets/17968114/21751516/d9a310e6-d5c8-11e6-8d6d-86f6fa0a41c5.png)

**Comment by iojw** [comment]
Bushes don't grow because they don't contain a PlantDefinition component unlike seeds. This shouldn't be a problem since in actual gameplay, players can't actually obtain the bush block 🙂. They can only plant the seeds, which takes care of the growth of the plant. If they do destroy a bush formed by a seed, they'll get back the seed.

**Comment by TimVerhaegen** [comment]
Wait people can right? When you break them? Hmhh I think yes.. Let me test that out. Will edit this comment to prevent spam.

**Comment by iojw** [comment]
@TimVerhaegen: To explain this further, the data for the growth stages is stored in the seed prefab. When you plant the seed and it grows, this data is transferred from the the current block to the next block. This is how each block in the growth stage knows what to grow into the next. 🙂 

When you use the /give command for a bush block, this bush block doesn't contain any data about the growth stages, thus it cannot grow. I'm not sure if there's any point to adding this in since this can't actually happen in a real game and also, adding it in would mean that you would have to copy the growth stages in the seed prefab to each of the bush prefabs, which might be a little tedious.

**Comment by TimVerhaegen** [comment]
Alright good to know :) thanks!
