### ISSUE TITLE
Question - Creating a new item?

### ISSUE THREAD

**Issue by kholyphoenix1** [Terasology/SimpleFarming#6]
Hello,

I need to create the 3D object?
What program can I build objects?
I watched you need programming in Java.

Could anyone guide me?
Thanks!

**Comment by Cervator** [comment]
Hi @kholyphoenix1 ! If you are specifically asking how to make items in Terasology then check out https://github.com/Terasology/TutorialAssetSystem for the basics.

You can make blocks, crops, etc just fine with that alone. If you're asking more in general then I'm not sure why this issue is in our SimpleFarming repo :-)

We have a few resources for how to *specifically* get 3D assets (blocks shapes or creature models) out of Blender into Terasology, such as http://forum.terasology.org/threads/blender-to-md5-howto.1020 - but that doesn't cover actual use of Blender itself, for instance.

May be best to come lurk on our IRC channel then ask on occasion there until you reach somebody able to help. But as far as creating assets right here for SimpleFarming that really takes nothing more than making 16x16 PNGs (or bigger) along with a bit of text in a definition file to make new crops. You can look around inside this repo for examples :)

**Comment by jellysnake** [comment]
Closing due to lack of response so it's probably solved
